@startuml CasoUsoDiagram
left to right direction
skinparam packageStyle rectangle

actor Usuario
actor "Nodo MOM" as Nodo

rectangle "Middleware MOM" {


    usecase "Autenticarse" as UC1
    usecase "Crear tópico" as UC2
    usecase "Eliminar tópico" as UC3
    usecase "Listar tópicos" as UC4
    usecase "Crear cola" as UC5
    usecase "Eliminar cola" as UC6
    usecase "Listar colas" as UC7
    usecase "Enviar mensaje a tópico" as UC8
    usecase "Enviar mensaje a cola" as UC9
    usecase "Recibir mensaje de tópico" as UC10
    usecase "Recibir mensaje de cola" as UC11
    usecase "Conexión permanente" as UC12
    usecase "Conexión temporal (sin estado)" as UC13


    usecase "Replicar mensajes" as UC14
    usecase "Particionar tópicos y colas" as UC15
    usecase "Recuperarse de fallos" as UC16
}

Usuario --> UC1
Usuario --> UC2
Usuario --> UC3
Usuario --> UC4
Usuario --> UC5
Usuario --> UC6
Usuario --> UC7
Usuario --> UC8
Usuario --> UC9
Usuario --> UC10
Usuario --> UC11
Usuario --> UC12
Usuario --> UC13

Nodo --> UC14
Nodo --> UC15
Nodo --> UC16
@enduml
